### ISSUE TITLE
Intercom example works only on Chrome

### ISSUE THREAD

**Issue by bmstefanski** [QwikDev/partytown#278]
- [ ] I am interested in helping provide a fix!

**Describe the bug**
The intercom example doesn't seem to work on Safari Desktop & Mobile, or Firefox. It works on Chrome though. 

**To Reproduce**
1. Go to https://partytown.builder.io/tests/integrations/intercom/
2. See if the Intercom widget pops up 

**Reproduction link**
https://partytown.builder.io/tests/integrations/intercom/

**Expected behavior**
Ideally, it should work on all modern browsers or throw an error with some descriptive message if it's due to the lack of a support for some feature

**Partytown version**
Not sure, the source code is located in the official repository, [here](https://github.com/BuilderIO/partytown/tree/main/tests/integrations/intercom)

**Additional context**
The official example was not working at all, even on Chrome a few months ago. Now only Chrome seems to work.

Firefox logs:
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/28964599/194569568-6c52ff05-f388-438e-9ec8-6fda17e65474.png">

Safari logs:
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/28964599/194569673-94f8cbd2-34a0-4f6e-9d9e-8873875334ac.png">

Thanks in advance for the response and **_an amazing library_**. Let me know if more details are needed :)

**Comment by public-hosting** [comment]
Unfortunately currently it does not work even in Chrome
```
frame-modern.5069da72.js:2141 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'map')
    at me (frame-modern.5069da72.js:2141:55)
    at async eval (frame-modern.5069da72.js:10014:19)
```

**Comment by maplessmann** [comment]
We are having a similar issue. The Intercom widget works, but if a user clicks on a message the widget disappears and Partytown throws this error:

```
TypeError: Cannot set property scrollTop of [object Object] which has only a getter
    at p (frame-modern.11044599.js:3:115138)
    at conversation_body_ConversationBody.scrollToBottom (app-modern.781a032c.js:6:175909)
    at conversation_body_ConversationBody.componentDidUpdate (app-modern.781a032c.js:6:177449)
    at as (vendors~app~tooltips-modern.41236692.js:4:129869)
    at gl (vendors~app~tooltips-modern.41236692.js:4:147472)
    at i.unstable_runWithPriority (vendors~app~tooltips-modern.41236692.js:4:167679)
    at Qo (vendors~app~tooltips-modern.41236692.js:4:91490)
    at Tl (vendors~app~tooltips-modern.41236692.js:4:144138)
    at sl (vendors~app~tooltips-modern.41236692.js:4:140292)
    at eval (vendors~app~tooltips-modern.41236692.js:4:91781)
```

@adamdbradley do you know this error?

**Comment by lsimone** [comment]
[The example](https://partytown.builder.io/tests/integrations/intercom/) does not work in Chrome either.

Is there any chance  this 5 months ago issue will be taken into account?

![image](https://user-images.githubusercontent.com/3266650/223652697-f703126e-a9c2-48b8-9464-0854e22aa82d.png)
